### ISSUE TITLE
Internal Server Error - Invalid Cast 

### ISSUE THREAD

**Issue by andrtose** [RHEAGROUP/CDP4-WebServices-Community-Edition#103]
Hello,

I'm trying to create a transaction where I create an Site Refrence data library, some categories, some Compound parametertypes(based on parameterstype present in the General RDL) other parameter typesand  some rules, when I write I have this exception:

_The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:Specified cast is not valid."_

With the following trace:

   _in CDP4ServicesDal.CdpServicesDal.<Write>d__9.MoveNext() in C:\Users\sgerene\Documents\15-Source-Code\CDP4\CDP4-SDK-Community-Edition\CDP4ServicesDal\CdpServicesDal.cs:riga 158
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in CDP4Dal.Session.<Write>d__47.MoveNext() in C:\Users\sgerene\Documents\15-Source-Code\CDP4\CDP4-SDK-Community-Edition\CDP4Dal\Session.cs:riga 493
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   in COSM.DataBaseManagement.WorkingSession.<Write>d__161.MoveNext() in C:\Users\a.tosetto\Documents\Work\SW_DEVELOPMENT\COSM3\COSM_Main\DataBaseManagement\WorkingSession.cs:riga 4158
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   in COSM.DataBaseManagement.SessionTransaction.<Write>d__18.MoveNext() in C:\Users\a.tosetto\Documents\Work\SW_DEVELOPMENT\COSM3\COSM_Main\DataBaseManagement\WorkingSession.cs:riga 4267_

Yesterday I try to comment the lines that create parameterstype, and it works, I try to uncommment the line that create the first compound parameter type and I have the exception but when I try again   (without any action) it works!

Thank you for your replay.

Andrea

**Comment by samatrhea** [comment]
@andrtose we will investigate and get back to you, i moved the issue to the server

**Comment by alexatrhea** [comment]
@andrtose would you be able to provide the code that is causing the issue?

**Comment by samatrhea** [comment]
> 
> 
> @andrtose would you be able to provide the code that is causing the issue?

yes that would help a lot in reproducing it on our side

**Comment by andrtose** [comment]
I'll try to create a simple project that reproduce the problem asap. Thank you!

**Comment by samatrhea** [comment]
thanks, that will help

**Comment by andrtose** [comment]
Instead to create a project I create a static class with a RunMe method. 
Maybe I'm doing something wrong creating components.

Please Note that if I try to create only one CompoundParameterType it works.
Here is the code:

`  using CDP4Common.CommonData;
   using CDP4Common.SiteDirectoryData;
   using CDP4Dal;
   using CDP4Dal.Operations;
   using System;
   using System.Collections.Generic;
   using System.Linq;
   using System.Text;
   using System.Threading.Tasks;

    public static class ReferenceDataLibraryTest
    {
        private static Session WorkingSession;

        public static async void RunMe(Session session)
        {
            WorkingSession = session; //  session shall be open

            var siteDirectory = WorkingSession.RetrieveSiteDirectory();
            SiteReferenceDataLibrary myRDL = siteDirectory.SiteReferenceDataLibrary.SingleOrDefault(rdl => !rdl.IsDeprecated && rdl.ShortName == "A_RDL_Generic6");


            IEnumerable<ReferenceDataLibrary> rdls;

            rdls = WorkingSession.RetrieveSiteDirectory().AvailableReferenceDataLibraries();

            if (rdls != null)
            {
                foreach (var rdl in rdls.ToList())
                {
                    await ReadThingFromRemote(rdl);
                    //t.Wait();
                }


            }
            var genericRdl = siteDirectory.SiteReferenceDataLibrary.Single(x => x.ShortName == "Generic_RDL");

            if (myRDL == null)
            {
                myRDL = new SiteReferenceDataLibrary(Guid.NewGuid(),WorkingSession.Assembler.Cache, new Uri( WorkingSession.DataSourceUri));
                myRDL.Name = "A Reference Data Library";
                myRDL.ShortName = "A_RDL_Generic6";
                myRDL.RequiredRdl = genericRdl;
                var context = TransactionContextResolver.ResolveContext(siteDirectory);
                var cloneContainer = siteDirectory.Clone(false);
                var transaction = new ThingTransaction(context);
                transaction.Create(myRDL, cloneContainer);
                await UpdateReferenceDataLibrary(transaction, myRDL);
                try
                {
                    await WorkingSession.Write(transaction.FinalizeTransaction());
                }
                catch (Exception ex)
                {
                    
                }
            }
            
        }
        public async static Task UpdateReferenceDataLibrary(ThingTransaction transaction,
            ReferenceDataLibrary clonedrdl)
        {
            #region Parameter Types Definition

            ParameterType CoG = CreateCompoundParameterType(clonedrdl, "Center of Gravity", "CoG",
                new Dictionary<string, string>() { { "x", "x" }, { "y", "y" }, { "z", "z" } }, null, transaction: transaction),
            Ref_Axes = CreateCompoundParameterType(clonedrdl, "Reference Coordinate Frame", "ref_axes",
                new Dictionary<string, string>() { { "posX", "x" }, { "posY", "y" }, { "posZ", "z" },
                                        { "rotX", "x" }, { "rotY", "y" }, { "rotZ", "z" }, {"parentName", "text" }}, null, transaction);
            
            #endregion

           
        }

        public static async Task<Thing> ReadThingFromRemote(Thing thing)
        {
            Lazy<Thing> updatedThing = null;

            var key = thing.CacheKey;
            try
            {
                if (thing is ReferenceDataLibrary)
                    await WorkingSession.Read(thing as ReferenceDataLibrary);
                else
                    await WorkingSession.Read(thing);
            }
            catch (Exception ex)
            {


            }
            if (WorkingSession.Assembler.Cache.TryGetValue(key, out updatedThing))
                return updatedThing.Value;
            else
                return null;
        }

        private static ParameterType CreateCompoundParameterType(ReferenceDataLibrary rdl, string parameterName, string parameterShortName, 
            Dictionary<string, string> componentsNames, Category cat, ThingTransaction transaction)
        {
            ParameterType type = rdl.ParameterType.SingleOrDefault(x => x.ShortName == parameterShortName);
            
            if (type == null)
            {
                CompoundParameterType compoundParameterType = new CompoundParameterType(Guid.NewGuid(),WorkingSession.Assembler.Cache, new Uri( WorkingSession.DataSourceUri));

                compoundParameterType.Name = parameterName;
                compoundParameterType.ShortName = parameterShortName;
                //paramTypes.Add(parameterShortName, parameterTypeComponent);
                compoundParameterType.Symbol = parameterShortName;
                if (cat != null && compoundParameterType.Category.SingleOrDefault(x => x.ShortName == cat.ShortName) == null)
                {
                    compoundParameterType.Category.Add(cat);
                }

                transaction.Create(compoundParameterType, rdl);
                //transaction.CreateThing(compoundParameterType, rdl);
                

                ParameterType ptype = null;

                var parametertypes = WorkingSession.OpenReferenceDataLibraries.SelectMany(rd => rd.ParameterType).ToList();
                foreach (KeyValuePair<string, string> t in componentsNames)
                {
                    ptype = rdl.ParameterType.SingleOrDefault(p => p.ShortName == t.Value);
                    if (ptype == null)
                    {
                        ptype = parametertypes.SingleOrDefault(x => x.ShortName == t.Value);
                    }

                    if (ptype != null)
                    {
                        var comp = CreateParameterTypeComponent(transaction, t.Key, ptype, compoundParameterType);
                        compoundParameterType.Component.Add(comp);
                    }
                }
                
                return compoundParameterType;
            }
            return type as CompoundParameterType; 
        }

        public static ParameterTypeComponent CreateParameterTypeComponent(ThingTransaction transaction, string ComponentShortName, ParameterType parameterType,
                CompoundParameterType compoundParameterType)
        {
            if (compoundParameterType == null)
            {
                throw new ArgumentNullException(nameof(compoundParameterType));
            }

            //var clone = compoundParameterType.Clone(false);
            ParameterTypeComponent component = null;
            QuantityKind qkind = parameterType as QuantityKind;
            if (compoundParameterType.Component.SingleOrDefault(x => x.ShortName == ComponentShortName) == null)
            {
                component = new ParameterTypeComponent(Guid.NewGuid(), WorkingSession.Assembler.Cache, new Uri(WorkingSession.DataSourceUri));

                component.ShortName = ComponentShortName;
                component.ParameterType = parameterType;
                component.Container = compoundParameterType;

                if (qkind != null)
                {
                    component.Scale = qkind.DefaultScale;
                }
                transaction.Create(component, compoundParameterType);
                
            }
            return component;
        }

    }`

**Comment by alexatrhea** [comment]
Thanks @andrtose we will take a look

**Comment by samatrhea** [comment]
@mmilitaru please take the resulting POST message and make it part of the integration test suite for testing there. Any issues on the SDK itself can be reported in another taks (new ticket) which needs to be resolved there.
