### ISSUE TITLE
Permissions - not allowed to add item to container if role only has read on container

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#13]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a role with MODIFY on ElementDefinition and READ on Iteration tries to add an ElementDefinition the service returns not allowed. This should not be the case

### Steps to Reproduce
Login using CDP4-IME and try to create an ElementDefinition for a role that has MODIFY on ElementDefinition and READ on Iteration

### System Configuration

- CDP4 Web Services version:
  - [x] CDP4Common:  1.2.0
  - [x] PostrgreSQL: 9.6.6
  - [x] CDP4WebServices.API: 1.0.2

**Comment by naron-rhea** [comment]
is that really not the expected behaviour? ElementDefinition is contained by Iteration, so by adding or removing one, iteration is actually modified as well

**Comment by samatrhea** [comment]
i tried again, i must have made a mistake will testing. I can also no longer reproduce this bug. Therefore i close it.
