### ISSUE TITLE
Implement DockerCompose file(s) for server database combinations

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#130]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In order to make docker deployment more straightforward a DockerFile needs need to be created. Two configurations are required, one for a test environment with the test database, and one for production deployment. 

  - a test environment 
  - a production deployment environment

Database container:
- Volume for the data

Services Container:
- Volume for Filestores
- Volume for logs

Make sure a custom sql file can be used on container startup.

Create/edit deployment documentation.

Alex fixes it and then shares it with the team.

### Steps to Reproduce
NA

### System Configuration
NA

**Comment by lxatrhea** [comment]
Alex knows more...
