### ISSUE TITLE
CDP4 Services fail to provide access with attached sql dump

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#131]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The services seem to have a problem with the attached sql dump. It can be used to reproduce the problem.

IT could be that the solution is to upgrade to the current version of the services

### System Configuration

- CDP4 Web Services version: CE 5.1.0 RC 4
  - [x] PostrgreSQL: 9.6.x

[cdp4-public-dump.sql.gz](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/files/4730420/cdp4-public-dump.sql.gz)

**Comment by lxatrhea** [comment]
Database works in the IME, but not with the default password. 
So it seems like the password had been changed.

Added some [documentation](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/wiki/Restore-default-admin-password) to the WebService GitHub wiki how to restore a admin password.
