### ISSUE TITLE
Acyclic Validation DerivedQuantityKind

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#159]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Implement Acyclic Validation for the DerivedQuantityKind class via quantityKindFactor.quantityKind property

See https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/wiki/Cyclic-Cycles. Once implemented add a link to the code where it is implemented.

### System Configuration

- CDP4 Web Services version: 6.0.0

**Comment by cozminvelciu** [comment]
Need to take a look over integration tests as well.
