### ISSUE TITLE
Acyclic Validation MeasurementScale

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#161]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Implement Acyclic Validation for the MeasurementScale class via:
* mappingToReferenceScale.referenceScaleValue.container
* mappingToReferenceScale.dependentScaleValue.container

See https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/wiki/Cyclic-Cycles. Once implemented add a link to the code where it is implemented.

### Steps to Reproduce
NA

### System Configuration

- CDP4 Web Services version: 6.0.0

**Comment by cozminvelciu** [comment]
Need to take a look over integration tests as well.
