### ISSUE TITLE
 Implement CDP4 version 1.2 stage 1

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#170]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Run code generation for CDP4 version 1.2 and create new Webservices version

**Comment by samatrhea** [comment]
did i not ask to NOT merge this?

**Comment by alexatrhea** [comment]
> did i not ask to NOT merge this?

My bad, I somehow got the impression that it was ok to merge.
