### ISSUE TITLE
Concurrency Issues when creating items

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#19]
[CDP4Server.log.gz](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/files/2263212/CDP4Server.log.gz)
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When operating on a server with multiple users on the same model sometimes the server responds with a duplicate key violation. 
  - Internal Server Error: "exception:23505: duplicate key value violates unique constraint \"Parameter_REV_PK\""
  - Internal Server Error: "exception:23505: duplicate key value violates unique constraint \"ElementDefinition_REV_PK\""

A log file is attached that has multiple of these kinds of exceptions

### Steps to Reproduce

From multiple sessions add the same kind of thing at the same time. 

### System Configuration

- CDP4 Web Services version:
  - [x] CDP4Common:  1.4.0
  - [x] CDP4 Web Server: 1.0.6
  - [x] PostrgreSQL: 9.6.9

**Comment by samatrhea** [comment]
it seems we are reading the revision of the topcontainer and we increment on a POST. This should be replaced by reading the next revision from a sequence. The side-effect of this is that there may be `missing` revision numbers, but this is acceptable.

**Comment by merlinatrhea** [comment]
The revision number of the TopContainer is being used in POST handling. The TopContainer revision number should only be used for Reads. For POST handling a new revision number (from sequence) must be retrieved which will be (by definition) save for concurrency handling.

**Comment by samatrhea** [comment]
fixed in 4dd63c59bb532bff34b2134b9dc17a5b4be685d0

**Comment by naron-rhea** [comment]
It seems like a new object is not inserted in the revision table anymore. As a result newly created objects are not returned on subsequent GET requests
