### ISSUE TITLE
When a new EngineeringModelSetup is created, the side-effect created IterationSetup has an empty description which is not allowed accordding to 10-25

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#37]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a new EngineeringModelSetup is created, the side-effect created IterationSetup has an empty description which is not allowed accordding to 10-25

### Steps to Reproduce
Create a new Engineering Model and verify that the first iteration has an empty description. I propose we set the description to `-`

**Comment by samatrhea** [comment]
any progress on this issue?

**Comment by naronatrhea** [comment]
shoudl be resolved

**Comment by samatrhea** [comment]
feel free to close then
