### ISSUE TITLE
Wrong Docker install instructions

### ISSUE THREAD

**Issue by danlub** [RHEAGROUP/CDP4-WebServices-Community-Edition#39]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Instructions for installing the web services with Docker do not work. I found a workaround, so you may want to update them.

Nowadays, the instructions say:

`docker run -p 5432:5432 -it -d --name cdp4-database-community-edition --net cdp4 cdp4-database-community-edition:1.2.0`

which doesn't work. Instead, one should use

`docker run -p 5432:5432 -it -d --name cdp4-database-community-edition --net cdp4 rheagroup/cdp4-database-community-edition:1.2.0`

that was obtained from the description at [Docker Hub](https://hub.docker.com/r/rheagroup/cdp4-database-community-edition/).

Same thing happens with the second image. It is needed to change

`docker run -p 5000:5000 -it -d --name cdp4-services-community-edition --net cdp4 cdp4-services-community-edition:1.0.3`

to 

`docker run -p 5000:5000 -it -d --name cdp4-services-community-edition --net cdp4 rheagroup/cdp4-services-community-edition:1.0.3`

**Comment by samatrhea** [comment]
@danlub thanks for spotting this mistake in the documentation. I have updated it as per your suggestion.
