### ISSUE TITLE
Copying an ElementDefinition with subscriptions leads to duplicate ParameterValueSets

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#40]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

derived from bug posted here https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/76

### Steps to Reproduce
With CDP4-IME:

Setup catalogue model with element definition, parameter
Set subscription for other domain
Copy the element definition
This led to error for subscribing domain

### System Configuration

- CDP4 Web Services version: 3.2.0

**Comment by naronatrhea** [comment]
After implementation of the copy server side, is this still applicable?

**Comment by samatrhea** [comment]
@MartinFijneman and @samatrhea will check if this is still an issue. If i am not mistaken, part of the problem may be that the services accept valuesets to be sent in a POST message. This is not allowed in 10-25 (see https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/wiki/Annex-C#parametervalueset), so we should check and potentially update the services to be inline.

**Comment by naronatrhea** [comment]
@samatrhea @MartinFijneman Is this still an issue?

**Comment by samatrhea** [comment]
This week we do our best to verify this

**Comment by MartinFijneman** [comment]
copied items on dev server for ED with parameters, containing subscriptions for multiple domains, from single domain etc.  Results as expected.

verified

Closing this issue and setting to done
