### ISSUE TITLE
not possible to delete specific engineering model

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-WebServices-Community-Edition#48]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

In preparation of project, created initial setup engineering models:
* project Base Model
* equipment Test Setup

These should be deleted from the server.

When trying to do this, tried to delete StarBracket Test Setup. In trying to delete this, I received an error message. Trying a second time (including trying after logout and login again), not possible to delete this.

Error message:
An error was produced when deleting the EngineeringModelSetup: The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:42P01: relation \"EngineeringModel_00000000_0000_0000_0000_000000000000.EngineeringModel_View\" does not exist"

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 2.0.2.0
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [X] Microsoft Excel (32/64 bit): 32-bit
  - [X] Windows OS (32/64 bit): 64 bit
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@naronatrhea  while fixing this I think it is worth investigating whether it makes sens to `delete` the things in the model. This may take a substantial amount of time to write each thing to the revision tables. It should be good enough to leave the **EngineeringModel** data as is and only _delete_ the **EngineeringModelSetup**

**Comment by naronatrhea** [comment]
@samatrhea we could also just delete the schema. do you want to leave it?

**Comment by samatrhea** [comment]
i think we need to leave so we can go back in time, it;s part of the latest version. So, i would leave it.
