### ISSUE TITLE
Export API: when 2 models are selected for export an exception occurs

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#54]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The CDP4 Services expose an export API where EnginereeringModels can be exported from. When one EngineeringModelSetup is selected, the service exports it successfully. When multiple models are selected to be exported an error occurs.

The following is in the log file:

`2019-07-05 09:25:05.0461|ERROR|CDP4WebServices.API.Services.EngineeringModelZipExportService.CreateZipExportFile|Failed to export the open session to 619f5d50-66d3-41bd-bc2b-b76573374ae7.zip. Error: An item with the same key has already been added. Key: SiteReferenceDataLibraries/bff9f871-3b7f-4e57-ac82-5ab499f9baf5.json.`

### Steps to Reproduce
  1. open webapp
  2. select more than one model to export
  3. notice that an error box is shown.

### System Configuration

- CDP4 Web Services version: 5.0.0-RC1
  - [ ] CDP4Common:  3.1.0
  - [ ] PostrgreSQL: 9.6.11
  - [ ] Other:

**Comment by alexatrhea** [comment]
The problem stems from adding an entry in the zip file on export that is already there.

CDP4WebServices.API.Services.EngineeringModelZipExportService

``
line 833: var zipEntry = zipFile.AddEntry(siteReferenceDataLibraryFilename, outputStream);
```
i think we need to wrap it into `if (!zipFile.ContainsEntry(siteReferenceDataLibraryFilename))`. And in fact we need to do this everywhere we use `AddEntry`!
