### ISSUE TITLE
Copying ElementDefinition with option dependent parameters leads to error

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-WebServices-Community-Edition#56]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4 Web Services
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Copying ElementDefinition with option dependent parameters leads to error:

The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:Value cannot be null.\nParameter name: iteration"

ED in target model not created

### Steps to Reproduce

Server dump included in ticket. Element trying to be copied over was:
All Parameter Types - With Values - With Subscriptions - Option Dependency
* owned by SE
* subscription from PWR
* values (manual, ref, computed)
latest change made, leading to error:
* in source model (exchange model), set option dependency for parameters (step 34 in CDP4 Development Testing 20190705.xlsx)
* drag and drop using Control-key from source model (exchange model) to target model (RT_20190705) (step 36 in CDP4 Development Testing 20190705.xlsx)

### System Configuration

- CDP4 Web Services version:
  - [X] CDP4Common:  5.0.0
  - [ ] PostrgreSQL: 
  - [ ] Other:       
- Environment (Operating system, version and so on):
- .NET Framework version:
- Mono version:
- Additional information:

[CDP4 Development Testing 20190705.xlsx](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/files/3362871/CDP4.Development.Testing.20190705.xlsx)
[20190705 1458 CDP4IME Copy ED with option dependent parameters.log](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/files/3362874/20190705.1458.CDP4IME.Copy.ED.with.option.dependent.parameters.log)

**Comment by samatrhea** [comment]
log file and sql dump attached 

[CDP4Server.zip](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/files/3362898/CDP4Server.zip)
[2019-07-05T15%3A12%3A00-CDP4-DEV.sql.gz](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/files/3362899/2019-07-05T15.3A12.3A00-CDP4-DEV.sql.gz)

**Comment by MartinFijneman** [comment]
TBD if separate or related issue:
additional testing performed -
created new ED with 2 parameters distance and mass, no values yet, but with option dependency for distance parameter

dropped item into other model RT_20190705.
problem: option dependency for distance parameter not taken over

**Comment by MartinFijneman** [comment]
next steps in testing:
In model "Exchange Testing"
* edited name of ElementDefinition to Exchange Test Item - with man value:
* provided manual value for distance (option dependent)
* published values
* dropped ED into model RT_20190705

this leads to error as indicated in report above.

[20190705 1747 CDP4IME - drop ED with option dependent parameter manual value.log](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/files/3363366/20190705.1747.CDP4IME.-.drop.ED.with.option.dependent.parameter.manual.value.log)


testing related to steps 52-55 of testing document:

[CDP4 Development Testing 20190705.xlsx](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/files/3363376/CDP4.Development.Testing.20190705.xlsx)

**Comment by samatrhea** [comment]
> 
> 
> TBD if separate or related issue:
> additional testing performed -
> created new ED (Exchange Test Item) with 2 parameters distance and mass, no values yet, but with option dependency for distance parameter
> 
> dropped item into other model RT_20190705.
> problem: option dependency for distance parameter not taken over

Both options and states are model dependent, so, only the *default* ParameterValueSets can be copied. So, that all the option values nor the state dependent values cannot be copied is expected.

**Comment by MartinFijneman** [comment]
Understood that states are dropped altogether, i.e. the state dependency of parameters is not taken over,  going to "default" parameterValueSet.

For option dependency: not keeping the valueSet itself is understood. It is not known how many options there are and what they mean.
What should be taken over however is the "option dependency" setting itself of parameters. In setting up a model from a catalogue e.g. I think having the ability to take this setting over to other models can be very useful in setting up a model from another model (e.g. template)

**Comment by naronatrhea** [comment]
When this was implemented it was agreed on that option and state dependency were not going to be taken over. Are you saying now that option -dependency should be taken over?
With what values, all to the source default value?

**Comment by MartinFijneman** [comment]
Indeed, the option-dependency has a strong value, as this may often be used for a specific part in the modelling (e.g. high level results for the design). For this, I think your suggestion is indeed appropriate:
* if an element definition is copied over with values, use the value of the default option
* otherwise the default "-"
