### ISSUE TITLE
Copying ED with parameters with values - link formula not copied over correctly

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-WebServices-Community-Edition#57]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4 Web Services
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Copying an ElementDefinition that has computed values: link formulas are copied over incorrectly, ordering shuffled wrt original:

Original model:

![image](https://user-images.githubusercontent.com/35371313/60732326-feeec280-9f49-11e9-8dae-95099503b1e8.png)

Resulting model:

![image](https://user-images.githubusercontent.com/35371313/60732297-f72f1e00-9f49-11e9-8a97-7b54729fefc3.png)

### System Configuration

- CDP4 Web Services version:
  - [ ] CDP4Common:  5.0.0
  - [ ] PostrgreSQL: 
  - [ ] Other:       
- Environment (Operating system, version and so on):
- .NET Framework version:
- Mono version:
- Additional information:

[20190705 1724 CDP4IME - Copy ED with values - incorrect link formulas.log](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/files/3363289/20190705.1724.CDP4IME.-.Copy.ED.with.values.-.incorrect.link.formulas.log)

**Comment by MartinFijneman** [comment]
this affects the proper functioning of the the workbook, which gave unexpected results for values and their formatting in the computed value column (for the workbook in which the cell names exist, these are given in the wrong cell: e.g. a boolean parameter is linked to launch date from calculation sheet. Mismatch in data types.

**Comment by naronatrhea** [comment]
I will just as a first step make sure the formula is not copied over by erasing it completely

**Comment by MartinFijneman** [comment]
After shortly discussing it: copying over the formula is only useful in one specific use case, where you want to have the exact same item in another model AND use the same calculation sheet. In a general case, this may well be copying over too much information. It may be a much better approach to not take over these formulas at all.

So starting with erasing the formulas seems to me a better approach in copying items in any case. If a users wants the links, these can be easily re-established through the intended workbook.
