### ISSUE TITLE
Verify that IterationSetup.IsDeleted behavior is as per 10-25

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#66]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Verify that when an IterationSetup is deleted that
  - set the IterationSetup.IsDeleted flag to true and then break out of delete handling (using onBeforeDelete SideEffect)
  - NOT delete the iteration object itself or any other thing
  - throw an exception if invoked on a non-frozen IterationSetup

An IterationSetup that has IsDeleted =true shall:
  - prevent any read of the associated Iteration data (on any level within the Iteration)
  - prevent listing of the Iteration (with corresponding IterationSetup.isDeleted=true) objects when requesting EngineeringModel.iteration listing

### Steps to Reproduce
NA

**Comment by kamilatrhea** [comment]
Verify that when an IterationSetup is deleted that

- [ ]  set the IterationSetup.IsDeleted flag to true and then break out of delete handling (using onBeforeDelete SideEffect)

- [ ]  NOT delete the iteration object itself or any other thing

- [x] throw an exception if invoked on a non-frozen IterationSetup

An IterationSetup that has IsDeleted =true shall:

- [ ]  prevent any read of the associated Iteration data (on any level within the Iteration)

- [ ] prevent listing of the Iteration (with corresponding IterationSetup.isDeleted=true) objects when 

requesting EngineeringModel.iteration listing

**Comment by kamilatrhea** [comment]
@samatrhea I fixed the first three points, for the last two do you want me to handle this on permission service level? Right now in the IME the deleted iterations correctly do not appear in the list of iterations you can open, and appear grey out in the engineering model browser.

**Comment by alexatrhea** [comment]
Make sure that the Iteration data is actually deleted. Update the integration test to check this explicitely.
