### ISSUE TITLE
Remove multiple build targets from the projects

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#69]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
All the projects in the solution multitarget dotnet frameworks, except for the **CDP4WebServer** project which targets net472. Since the projects are only hosted by the CDP4WebServer it doesn't make sense *(anymore) to multitarget the other projects. All projects shall target net472 or netstandard.

### Steps to Reproduce
NA

### System Configuration

- CDP4 Web Services version: 5.0.0

**Comment by samatrhea** [comment]
diff up at D1516

**Comment by alexatrhea** [comment]
<devops> tag was there because this this improvement helps us downstream to make better automation too. Anyway, accepted to merge on my side.
