### ISSUE TITLE
Check whether logging in with empty password is possible on the server, if it is investigate corrective actions.

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#78]
Currently in IME and server you are capable of creating a Person with no password. However, the IME actively forbids logging in without a password. It is unclear whether the server disallows this also. Investigate and propose consolidation.

**Comment by samatrhea** [comment]
fiest part of this task is to investigate what happens when a Person exists without a password set (null) and then trying to access the server with that Person without providing a password. This should not be allowed.

**Comment by lxatrhea** [comment]
When a person is created in the IME without a password (or changed to empty), the Password is not sent to the server in the request to the webservice. 
Password is therefore null in the WebService and the WebService creates a random password (32 bytes) that nobody knows. The Person is unable to log in.
So far so good...

However, you could create a Person creation request using an empty string as a password.
In this case, the password is not null in the WebService, so correctly hashed/salted credentials could be created AND also used in the Webservice.
I will change the null check in the WebService to a string.IsNullOrWhitespace check, so empty means: Create an unknown password, so the Parson cannot login.
