### ISSUE TITLE
Deprecating a PersonRole resets all ParticipantPermissions on the server to NOT_APPLICABLE

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#81]
Behavior first noticed on dev server. Deprecating a ParticipantRole seems to set ALL participant permissions (even those of other roles) to `NOT_APPLICABLE` barring access to all EngineeringModel data until fixed.

**Comment by lxatrhea** [comment]
Works fine in my local environment.

**Comment by alexatrhea** [comment]
Suspicion now has been cast on a newly introduced IME bug.

**Comment by alexatrhea** [comment]
Bug was found to be a moved subscription which was triggered too early. Removing editability of permission rows solves this.

Issue solved and will be closed when https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pull/247 is merged.

**Comment by samatrhea** [comment]
so, was it a problem on the server or in the IME?

**Comment by alexatrhea** [comment]
The problem was the IME. A reactive subscription that I moved inevitably fired too early and caused the inline edit behavior to send a post message to server with wrong state.

**Comment by alexatrhea** [comment]
Fixed with inline edit behavior gone.
