### ISSUE TITLE
WEBSERVICE: Opening EM for participants without domain assignment leads to internal server error - improve checking mechanism and user feedback

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#94]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
IME Issue [#184](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/184) results into changes for IME, SDK and Webservice.

When an already completed Npgsql transaction is rolled back (or committed) again, an error is thrown. 
When the transaction was already rolled back because of some error, that Transaction error is the last error, and will be placed in the HTTP Reponse body.
This way, the initial error is not visible to the client, but the Transaction error.
We want the original error message in the HTTP response body.

**Comment by samatrhea** [comment]
lets make sure there is no longer an internal error. In principle we should not allow a particiant with zero domains, 10-25 specifies the following:


Participant:
domain | DomainOfExpertise [1..*] |   | references to the domains of expertise (set of DomainOfExpertise) that this Participant may represent Note: At any moment in a session in an E-TM-10-25 compliant environment a Participant is actively representing one DomainOfExpertise only, see the selectedDomain property. If more than one DomainOfExpertise is specified, he or she may select any of those DomainOfExpertises to switch to, at any time during the session.
